### ISSUE TITLE
Server Crash without log/crashdump

### ISSUE THREAD

**Issue by teracube** [CortexPE/TeaSpoon#172]
## Issue Description

since issue the #136 not solved i can not use TeaSpoon on my server because server crash ramdomly.
i tried reproduce this issue unsuccessfuly.

there is no trace no log or crashdump
if i removed TeaSpoon the server do not crash
i tried all latest PMMP and TeaSpoon version

my server is hosted and i can not used linux command . i have just a rcon panel

is there a way to record/track the error (with a plugin )?
is it a map problem or incomptability with TeaSpoon

sorry i'm a newbies 
sorry for my bad english

thanks

@desesparate gamer

## Steps to Reproduce

1. ...
2. ...
3. ...

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by SuperKali** [comment]
this is for blame the boat item, please @CortexPE fix this

**Comment by CortexPE** [comment]
test it on Latest commit...

**Comment by teracube** [comment]
@CortexPE not solved with latest commit my server crash and no error or crashdump

@SuperKali not solved for me with latest commit and you ?

**Comment by teracube** [comment]
@SuperKali
have you tested latest commit ... 
thanks

**Comment by CortexPE** [comment]
I need steps to reproduce

**Comment by teracube** [comment]
@CortexPE 
sorry i can not reproduce this issue
i tried without success
i'm sure this is a TeaSpoon issue because i removed TeaSpoon during 5 days and no crash.
Then today i install TeaSpoon and server crash after 4 hours.
no trace, no log or crashdump
am I the only one to have this problem ?

**Comment by CortexPE** [comment]
> am I the only one to have this problem ?

Probably, @teracube xD

**Comment by BajanVlogs** [comment]
Just use TeaSpoon have players join your server happens to me also

**Comment by BajanVlogs** [comment]
Version #106 dev works fine no crashes then #107 - #109 starts the crashes

**Comment by BajanVlogs** [comment]
thats for the poggit builds up above

**Comment by teracube** [comment]
on my server crash start with commit Dev #83 (&80b4) or Dev #82 (&80b2)
https://poggit.pmmp.io/r/19204/TeaSpoon_dev-83.phar

since, all the versions make my server crash without any log or crashdump

i had opened issues #136 and this issue

I try for a month to reproduce the problem without success

**Comment by BajanVlogs** [comment]
Its Dev #107 that causes the crash

**Comment by CortexPE** [comment]
I'll try to deploy a test server on my VPS and see when it'll crash w/o restart

**Comment by CortexPE** [comment]
(I usually restart my server every 2-3 hours)

**Comment by TDMidkwhatisxd** [comment]
it freeze because of dktapps xp commit

**Comment by CortexPE** [comment]
> it freeze because of dktapps xp commit

Maybe?

btw my test server is still running without problems...
![image](https://user-images.githubusercontent.com/17762324/35515655-5cd083be-04cf-11e8-89f8-f690d768eb99.png)

so maybe @TDMidkwhatisxd is right? because you can't have XPOrbs on a completely blank test server xd

**Comment by FaanMaario** [comment]
Actually I tested and from what I did (throw bottles of experience), and my server start lagging and... freeze.

**Comment by CortexPE** [comment]
![new bitmap image](https://user-images.githubusercontent.com/17762324/35563539-9ae3efa8-057c-11e8-9c55-5eec4442050f.png)

**Comment by FaanMaario** [comment]
I created a test server and strangely, nothing happen when I throw a lot of xp bottle

**Comment by optimusprime338** [comment]
@FaanMaario bring 40+ players in your test server then it will happen:)

**Comment by optimusprime338** [comment]
And cant blame teaspoon being 100% sure since my other servers got same issue without this plugin too!

**Comment by teracube** [comment]
As I've already said in my case,  my server crash since TeaSpoon version > commits f60a288 
TeaSpoon_dev-81 or TeaSpoon_dev-83 (with any PMMP version > dev-554)

since this commit server crash/freeze randomly  if Teaspoon is loaded.  sometimes server crash with 2 players to 25 players after 5 minutes to 4 hours...

If i remove TeaSpoon, no crash 

a player told me that server crashed after mining wood and boat build.
but i can't reproduce this

sorry for my very bad english..

**Comment by CortexPE** [comment]
boats caused the crash before but boats were removed in later builds... (they still exist but they don't do anything anymore)

**Comment by optimusprime338** [comment]
@CortexPE I am sure this is because of mobs! since I used pureentitiesX and teaspoon for mobs only! and both gave me same problems!

**Comment by TDMidkwhatisxd** [comment]
That plugin froze with few mobs, I limited to max 5-6 mobs and still froze

**Comment by teracube** [comment]
@everybody
your server crash or freeze
in my case, my server crash

**Comment by optimusprime338** [comment]
@teracube Please update your pmmp to latest build!!! hopefully that will solve your problem:)

**Comment by tiNsLeY799** [comment]
Just download AutoClearLagg. It removes entities every five minutes or so. I've got it, and the only thing that crashed my server was BlockPets.

**Comment by BajanVlogs** [comment]
Yeah AutoClearLagg doesn't help its the xp that's doing it when I don't use teaspoon server is fine and no crashes but when I use teaspoon it crashes
it doesn't crash on dev phar #110

**Comment by teracube** [comment]
i tested to day 
https://poggit.pmmp.io/r/22012/TeaSpoon_dev-130.phar
https://jenkins.pmmp.io/job/PocketMine-MP/668/artifact/PocketMine-MP.phar

and my server crash after 3 hours with 6 players
and no log

**Comment by FaanMaario** [comment]
With the latest TeaSpoon and pmmp commit, my Minecraft server has not been freezed for 14 hours.
![croquis 3](https://user-images.githubusercontent.com/10689456/35776314-58f63a66-099a-11e8-936c-70d9e98605e8.png)

**Comment by CortexPE** [comment]
@ everyone What are your servers' specifications?

**Comment by teracube** [comment]
@CortexPE 

server is hosted

PocketMine-MP version: 1.7dev #675
uname -a: Linux game01 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64
PHP Version: 7.2.0
Zend version: 3.2.0
OS : Linux

3 worlds (lobby, minage, faction)

**Comment by optimusprime338** [comment]
@teracube Ram doesnt matter! do you about what type of CPU you use?

**Comment by teracube** [comment]
@optimusprime338 
CPU Intel i7-7700K 4,7GHz
4024M RAM is sufficient for 50 slots

this issue  has nothing to do with RAM or CPU because sometimes my server crash with 2 or 5 players
My server never crash if TeaSpoon is removed

**Comment by FaanMaario** [comment]
Mine is hosted on a VPS with CPU 2 Cores, 4GB RAM.

**Comment by BajanVlogs** [comment]
you have to have mobs on and kill mobs for they drop exp
then watch the server get laggy then watch it freeze

**Comment by CortexPE** [comment]
@ everyone can you guys test this on latest commit with these configurations:

```yaml
Xp:
 # ExperienceOrb Override -- Enabling this will override PMMP's ExperienceOrb entity
 override: true
 dropMobExperience: true
 # Toggle to enable/disable pickup delay when picking up XPOrbs (true in Vanilla-MineCraft) [NEEDS OVERRIDE TO BE ENABLED]
 pickupDelay: false
 # Ticks till despawn -- 1 Second = 20 Ticks [NEEDS OVERRIDE TO BE ENABLED]
 ticksTillDespawn: 200
```

**Comment by LagHD** [comment]
I'll go test with 200 ticksTillDespawn & report in the Discord Group in #teaspoon channel

**Comment by CortexPE** [comment]
is this fixed yet @teracube ?

**Comment by CortexPE** [comment]
there isn't a config for generators :/

**Comment by xXNiceAssasinl0** [comment]
LOL

**Comment by teracube** [comment]
@CortexPE 
thanks for your great job and plugin

1/so can use standard configuration of the TeaSpoon config.yml or should stay on this test configuration
 
2/so you confirm that ender generator is correct like TeaSpoon do 
( some players tell me that before there were islands automaticaly generated by teaspoon, it's fale i suppose)

**Comment by teracube** [comment]
Update

server crash after 3 hours with the standard config
```
Xp:
 # ExperienceOrb Override -- Enabling this will override PMMP's ExperienceOrb entity
 override: false
 dropMobExperience: true
 # Toggle to enable/disable pickup delay when picking up XPOrbs (true in Vanilla-MineCraft) [NEEDS OVERRIDE TO BE ENABLED]
 pickupDelay: true
 # Ticks till despawn -- 1 Second = 20 Ticks [NEEDS OVERRIDE TO BE ENABLED]
 ticksTillDespawn: 6000

```

server don't crash with test config

```
Xp:
 # ExperienceOrb Override -- Enabling this will override PMMP's ExperienceOrb entity
 override: true
 dropMobExperience: true
 # Toggle to enable/disable pickup delay when picking up XPOrbs (true in Vanilla-MineCraft) [NEEDS OVERRIDE TO BE ENABLED]
 pickupDelay: false
 # Ticks till despawn -- 1 Second = 20 Ticks [NEEDS OVERRIDE TO BE ENABLED]
 ticksTillDespawn: 200
```
